name: Pull Request
description: "New PR"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Thank you for improving Nushell. Please, check our [contributing guide](../CONTRIBUTING.md) and talk to the core team before making major changes.
      placeholder: |
        Description of your pull request goes here. **Provide examples and/or screenshots** if your changes affect the user experience.
        Example: I am trying to do [...] but [...]
    validations:
      required: false
  - type: textarea
    id: changes
    attributes:
      label: "User-Facing Changes"
      description: List of all changes that impact the user experience here. This helps us keep track of breaking changes.
    validations:
      required: false
  - type: textarea
    id: tests_and_formatting
    attributes:
      label: "Tests + Formatting"
      description: ""A clear and concise description of any alternative solutions or features you've considered."
      placeholder: |
        "Make sure you've run and fixed any issues with these commands:"

        - `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
        - `cargo clippy --workspace -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
        - `cargo test --workspace` to check that all tests pass
        - `cargo run -- crates/nu-utils/standard_library/tests.nu` to run the tests for the standard library

        > **Note**
        > from `nushell` you can also use the `toolkit` as follows
        > ```bash
        > use toolkit.nu  # or use an `env_change` hook to activate it automatically
        > toolkit check pr
        > ```
    validations:
      required: false
  - type: textarea
    id: after
    attributes:
      label: "After Submitting"
      description: If your PR had any user-facing changes, update [the documentation](https://github.com/nushell/nushell.github.io) after the PR is merged, if necessary. This will help us keep the docs up to date.
    validations:
      required: false

