name: Pull Request
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: yeah
      placeholder: "foo"
        Example: "bar"
    validations:
      required: false
