name: Install pre-compiled clang-15

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Pull the binary archive for clang-15
        run: curl -fLo /tmp/clang-15.tar.xz https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.5/clang+llvm-15.0.5-x86_64-linux-gnu-ubuntu-18.04.tar.xz

      - name: Extract the archive
        run: tar xvf /tmp/clang-15.tar.xz --directory /tmp/

      - name: Check archive
        run: ls /tmp/clang+llvm-15.0.5-x86_64-linux-gnu-ubuntu-18.04/

      - name: Install the binaries
        run: |
          mkdir -p ~/.local/share/clang-15/
          cp -rv /tmp/clang+llvm-15.0.5-x86_64-linux-gnu-ubuntu-18.04/ ~/.local/share/clang-15/

      - name: Check the installation
        run: |
          ls ~/.local/share
          ~/.local/share/clang-15/bin/clang --version

