name: Install pre-compiled clang-15

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install clang-15
        run: |
          curl -fLo /tmp/clang-15.tar.xz https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.5/clang+llvm-15.0.5-x86_64-linux-gnu-ubuntu-18.04.tar.xz
          mkdir -p ~/.local/share/clang-15/
          tar xvf /tmp/clang-15.tar.xz ~/.local/share/clang-15

      - name: Check the installation
        run: ~/.local/share/clang-15/bin/clang --version

