name: Install OBNC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clone the source
        run: git clone https://github.com/oberonproject/obnc.git

      - name: Install the dependencies
        run: sudo apt install libgc-dev libsdl1.2-dev

      - name: Checkout to the source
        run: |
          cd obnc
          git checkout dev

      - name: Install the transpiler
        run: |
          ./build
          sudo ./install
          obnc -v
