name: A test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: See the content of `bashrc`
        run: cat ~/.bashrc

      - name: Add the dummy command
        run: echo "alias dummy=\"echo 'this is dummy'\"" >> ~/.bashrc

      - name: See the content of `bashrc`
        run: cat ~/.bashrc | tail

      - name: Check dummy command
        run: dummy
